### ISSUE TITLE
Glava color define with pywal

### ISSUE THREAD

**Issue by Teenarp2003** [LiteracyFanatic/not-dot#1]
Hello there.. I was trying to find how i could make glava color scheme compatible with pywal.. I saw you opened an issue on the official glava repo #138. I was having difficulty understanding what to do to dynamically adjust colors. The  --pipe flag on the stable version does not work. I saw a script in this repo named glava-colors which takes the colors from the .json file in .cache/wal with jq and saves into the fifo file.. I did not understand the full workings of the script. Can you provide me some insight into this? would greatly appreciate your help!

**Comment by LiteracyFanatic** [comment]
Here is a commented version of the script. Basically it just lets you send commands similar to those specified in the default shader files to glava while it's running. You can probably actually do a lot more than just setting the color like this, but I don't really understand OpenGL, so that's as far as I went. Hope this helps.

```bash
# Create a variable with the path to the FIFO (First-In-First-Out Queue) we want to use. $XDG_RUNTIME_DIR is a standard location on many Linux distros that is similar to /tmp but only accessible by the current user. It should be a path like /run/user/1000.
fifo="$XDG_RUNTIME_DIR/glava.fifo"
# Test to see if the FIFO already exists. If the test fails, execute the other half of the || statement and create it.
[[ -e "$fifo" ]] || mkfifo "$fifo"
# Read data from the FIFO and pipe it into the glava executable. & puts the whole line into the background so that the rest of the script can run. glava will execute newline separated commands written to the FIFO.
tail -f "$fifo" | /bin/glava --stdin &
# Get the desired color from the pywal cache. --raw-output just removes the quotes from around the value
foreground="$(jq --raw-output '.colors.color2' "$XDG_CACHE_HOME/wal/colors.json")"
# Write the color to the FIFO. glava interprets it as a command to set foreground color of the bars in the visualization.
echo "$foreground" >> "$fifo"
```

**Comment by Teenarp2003** [comment]
This works! Thank you so much for your time .

**Comment by LiteracyFanatic** [comment]
Glad I could help!
